# Generated by Django 5.2.8 on 2025-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='signup_Confirm_Password',
            new_name='signup_confirm_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='signup_Email',
            new_name='signup_email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='signup_Password',
            new_name='signup_password',
        ),
    ]
