# Generated by Django 5.2.8 on 2025-11-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_rename_signup_confirm_password_signup_signup_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='signup_confirm_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='signup_password',
            field=models.CharField(max_length=128),
        ),
    ]
