# Generated by Django 5.2.8 on 2025-11-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login_Email', models.CharField(max_length=50)),
                ('Login_Password', models.CharField(max_length=8)),
            ],
        ),
    ]
