# Generated by Django 5.2.8 on 2025-11-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Login_Email',
            new_name='login_email',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='Login_Password',
            new_name='login_password',
        ),
    ]
