# Generated by Django 5.2.8 on 2025-12-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0008_remove_newchat_ai_file_remove_newchat_user_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newchat',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
