# Generated by Django 5.2.8 on 2025-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0009_newchat_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newchat',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
