# Generated by Django 5.2.8 on 2026-01-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newchat', '0010_alter_newchat_uploaded_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewChat',
        ),
    ]
