# Generated by Django 5.2.8 on 2025-12-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0002_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
