# Generated by Django 5.2.8 on 2025-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_uploads/'),
        ),
    ]
