# Generated by Django 5.2.8 on 2026-01-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ai_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
