# Generated by Django 5.2.8 on 2026-01-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_ai_message_alter_history_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ai_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_message',
            field=models.TextField(),
        ),
    ]
