# Generated by Django 6.0.2 on 2026-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_history_ai_message_alter_history_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
